<?xml version="1.0" encoding="utf-8"?><Database Name="TPG2" Class="ConexionDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=TPG2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TPG2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Alumnos" Member="Alumnos">
    <Type Name="Alumno">
      <Column Name="id_alumno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dni" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="turno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comentarios" Member="Comentarios">
    <Type Name="Comentario">
      <Column Name="id_comentario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dni" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="texto" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>